spring:
  datasource:
    url: jdbc:sqlserver://employee1103.database.windows.net:1433;database=helloworlddb;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: trupti
    password: Pritesh@9998
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update 
      dialect: org.hibernate.dialect.SQLServer2012Dialect
      
server:
  port: 9191